jobs:
  build:
    docker:
      - image: buildpack-deps:trusty
    environment:
      FOO: bar
    parallelism: 3
    #resource_class: large
    working_directory: ~/sample-angular-project
    branches:
      only:
        - master
        - /rc-.*/
    steps:
      - run: make test
      - run: make
