jobs:
  build:
    docker:
      - image: circleci/node:10.16.3
    branches:
      only:
        - master
    steps:
      - run:
          name: "Build the application"
          #command: npm install
          command: npm run build
