version: 2.1
jobs:
  build:
    branches:
      only:
        - master
  build:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - checkout
      - run:
          name: "Testing"
          command: echo "Hi"