workflows:
    version: 2
    # the test workflow
    test_workflow:
        jobs:
            - deploy:
                filters:
                    branches:
                        only:
                            - develop
                            - staging
                            - master