jobs:
  build:
    docker:
      - image: circleci/node:10.16.3
    working_directory: ~/repo
    environment:
      FOO: bar
    #parallelism: 3
    #resource_class: large
    branches:
      only:
        - master
    steps:
      - run:
          name: "Npm install"
          #command: npm install
          command: npm run build
